openapi-mode = "follow-privileges"
openapi-security-active = false
db-uri = "postgres://api_user@127.0.0.1:5432/partout_nhtsa"
db-schemas = "vpic,api_reference"
db-anon-role = "web_anon"
server-host = "127.0.0.1"
server-port = 3005
